apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-horizon-traffic-deployment
spec:
  replicas: 1 # Ajustado a dos réplicas para mayor disponibilidad
  selector:
    matchLabels:
      app: secure-horizon-traffic
  template:
    metadata:
      labels:
        app: secure-horizon-traffic
    spec:
      containers:
        - name: secure-horizon-traffic-container
          image: gcr.io/securehorizon-419122/network-traffic:NTI
          ports:
            - containerPort: 3002 # Puerto en el que escucha tu aplicación

---
apiVersion: v1
kind: Service
metadata:
  name: secure-horizon-traffic-service
spec:
  selector:
    app: secure-horizon-traffic
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: LoadBalancer
